name: Build and Test

on:
  push:
    tags-ignore:
      - '*'
    branches:
      - '*'

jobs:
  buid-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: docker compose up
        run: make docker-up

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
          java-package: jdk
          architecture: x64

      - uses: DeLaGuardo/setup-clojure@master
        with:
          cli: latest

      - uses: 0918nobita/setup-cljstyle@v0.5.4
        with:
          cljstyle-version: '0.15.0'

      - uses: DeLaGuardo/setup-clj-kondo@master
        with:
          version: '2023.02.17'

      - name: Show versions
        run: |
          java -version
          clojure --version
          cljstyle version
          clj-kondo --version

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: clj-cache-${{ hashFiles('**/deps.edn') }}
          restore-keys: |
            clj-cache-

      - name: Lint
        run: make lint

      - name: Test
        env:
          AWS_REGION: ap-northeast-1
          AWS_ACCESS_KEY_ID: dummy
          AWS_SECRET_ACCESS_KEY: dummy
        run: make test
